#!/bin/bash

WERCKER_RANCHER_INSERVICE_UPGRADE_DOCKER_IMAGE="quay.io/kollekt/instore-data"
WERCKER_RANCHER_INSERVICE_UPGRADE_ACCESS_KEY="53DD543D591B064C0F7F"
WERCKER_RANCHER_INSERVICE_UPGRADE_SECRET_KEY="qB1XpbBW1dhYjVakSFWv2yyh58SaR6MmoazjajLB"
WERCKER_RANCHER_INSERVICE_UPGRADE_RANCHER_URL="ec2-52-30-124-64.eu-west-1.compute.amazonaws.com:8080/v1/projects/1a5"
WERCKER_RANCHER_INSERVICE_UPGRADE_HTTPS="false"
WERCKER_RANCHER_INSERVICE_UPGRADE_TAG="sometag"
WERCKER_RANCHER_INSERVICE_UPGRADE_STACK_NAME="instore-backend"
WERCKER_RANCHER_INSERVICE_UPGRADE_USE_TAG="true"

if [ "$WERCKER_RANCHER_INSERVICE_UPGRADE_HTTPS" == true ]; then
    export DTR_PROTO=https;
else
    export DTR_PROTO=http;
fi

function get_env_id { curl -s "$DTR_PROTO://$WERCKER_RANCHER_INSERVICE_UPGRADE_ACCESS_KEY:$WERCKER_RANCHER_INSERVICE_UPGRADE_SECRET_KEY@$WERCKER_RANCHER_INSERVICE_UPGRADE_RANCHER_URL/environments?name=$WERCKER_RANCHER_INSERVICE_UPGRADE_STACK_NAME" | "$WERCKER_STEP_ROOT/jq" '.data[0].id' | sed s/\"//g; }

DTR_ENV_ID=$(get_env_id)

sed -i -e "s/$WERCKER_RANCHER_INSERVICE_UPGRADE_DOCKER_IMAGE/$WERCKER_RANCHER_INSERVICE_UPGRADE_DOCKER_IMAGE:$WERCKER_RANCHER_INSERVICE_UPGRADE_TAG/g" docker-compose.yml

# get rancher-compose cli
curl -o rancher-compose.zip "$DTR_PROTO://$WERCKER_RANCHER_INSERVICE_UPGRADE_ACCESS_KEY:$WERCKER_RANCHER_INSERVICE_UPGRADE_SECRET_KEY@$WERCKER_RANCHER_INSERVICE_UPGRADE_RANCHER_URL/environments/$DTR_ENV_ID/composeconfig"

# unzip
unzip -o rancher-compose.zip

"$WERCKER_STEP_ROOT/rancher-compose" \
  --url "$DTR_PROTO://$WERCKER_RANCHER_INSERVICE_UPGRADE_RANCHER_URL" \
  --access-key "$WERCKER_RANCHER_INSERVICE_UPGRADE_ACCESS_KEY" \
  --secret-key "$WERCKER_RANCHER_INSERVICE_UPGRADE_SECRET_KEY" \
  --project-name "$WERCKER_RANCHER_INSERVICE_UPGRADE_STACK_NAME" \
  up --upgrade --pull -c --interval 3000 --batch-size 1
